plugins {
    id 'java-library'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(JavaCompile) {
    options.annotationProcessorGeneratedSourcesDirectory = file("$buildDir/generated/sources/annotationProcessor/java/main")
    options.incremental = true
    options.encoding = "UTF-8"
}

eclipse.project.name = appName + "-annotations"